
import React, { useState, useCallback, useMemo, useEffect } from 'react';
import { Policy, DocumentObject, DocumentStatus, DocumentContent } from './types';
import { POLICIES_DATA } from './constants';
import { generatePolicyDocument } from './services/geminiService';
import { useTranslation } from './context/LanguageContext';
import Header from './components/Header';
import DocumentList from './components/Dashboard';
import DocumentViewer from './components/DocumentViewer';
import LoadingSpinner from './components/LoadingSpinner';
import ComplianceJourney from './components/ComplianceJourney';
import Sidebar from './components/Sidebar';
import ComplianceDashboard from './components/ComplianceDashboard';
import LiveAssistant from './components/LiveAssistant';
import RiskAssessment from './components/RiskAssessment';
import { View } from './types';

const LOCAL_STORAGE_KEY = 'hrsd-documents';

const App: React.FC = () => {
    const [documents, setDocuments] = useState<DocumentObject[]>(() => {
        try {
            const savedDocs = localStorage.getItem(LOCAL_STORAGE_KEY);
            if (savedDocs) {
                return JSON.parse(savedDocs);
            }
        } catch (error) {
            console.error("Failed to load documents from localStorage", error);
            localStorage.removeItem(LOCAL_STORAGE_KEY);
        }
        return [];
    });
    
    const [currentView, setCurrentView] = useState<View>('complianceDashboard');
    const [selectedDocumentId, setSelectedDocumentId] = useState<string | null>(null);
    const [isInitializing, setIsInitializing] = useState<boolean>(documents.length === 0);
    const [error, setError] = useState<string | null>(null);
    const { language } = useTranslation();

    const policies: Policy[] = useMemo(() => Object.keys(POLICIES_DATA).map(key => ({
        id: key,
        title: key.replace(/([A-Z])/g, ' $1').trim(),
        frameworkText: POLICIES_DATA[key as keyof typeof POLICIES_DATA],
    })), []);

    useEffect(() => {
        document.documentElement.lang = language;
        document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    }, [language]);

    useEffect(() => {
        if (documents.length > 0) {
            try {
                localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(documents));
            } catch (error) {
                console.error("Failed to save documents to localStorage", error);
            }
        }
    }, [documents]);

    useEffect(() => {
        if (documents.length > 0) {
            setIsInitializing(false);
            return;
        }

        const initializeDocuments = async () => {
            setError(null);
            try {
                const newDocs: DocumentObject[] = [];
                const now = new Date();
                
                for (const [index, policy] of policies.entries()) {
                    try {
                        const content = await generatePolicyDocument(policy.title, policy.frameworkText);
                        const docTimestamp = new Date(now.getTime() + index * 1000).toISOString();
                        
                        newDocs.push({
                            id: `HRSD-${Date.now() + index}`,
                            policyTitle: policy.title,
                            content,
                            status: 'Draft',
                            version: 1,
                            createdAt: docTimestamp,
                            updatedAt: docTimestamp,
                            history: [{ timestamp: docTimestamp, status: 'Draft', notes: 'Document automatically generated by Agent AI.' }],
                        });
                    } catch (generationError) {
                         console.error(`Failed to generate document for: ${policy.title}`, generationError);
                    }
                }
                
                if (newDocs.length === 0 && policies.length > 0) {
                    throw new Error("All document generations failed.");
                }

                setDocuments(newDocs);

            } catch (err) {
                console.error("Initialization failed:", err);
                setError('Failed to generate initial documents. Please check your API key and network connection, then refresh the page.');
            } finally {
                setIsInitializing(false);
            }
        };

        if (documents.length === 0) {
            initializeDocuments();
        }
    }, [policies, documents.length]);


    const handleUpdateDocument = useCallback((docId: string, status: DocumentStatus, notes: string) => {
        setDocuments(docs => docs.map(doc => {
            if (doc.id === docId) {
                const now = new Date().toISOString();
                const newVersion = (status === 'Revisions Requested' || status === 'Draft') ? doc.version + 0.1 : doc.version;
                return {
                    ...doc,
                    status,
                    version: parseFloat(newVersion.toFixed(1)),
                    updatedAt: now,
                    history: [...doc.history, { timestamp: now, status, notes }],
                };
            }
            return doc;
        }));
    }, []);
    
    const handleViewDocument = (docId: string) => {
        setSelectedDocumentId(docId);
        setCurrentView('viewer');
    };

    const handleHomeClick = () => {
        setSelectedDocumentId(null);
        setCurrentView('complianceDashboard');
    }
    
    const setView = (view: View) => {
        setSelectedDocumentId(null);
        setCurrentView(view);
    }

    const renderContent = () => {
        if (isInitializing) {
             return <div className="flex-grow w-full flex items-center justify-center"><LoadingSpinner isInitializing={true} policyCount={policies.length} /></div>;
        }

        if (error) {
            return <div className="flex-grow w-full flex items-center justify-center text-center text-red-400"><p>{error}</p></div>;
        }

        switch (currentView) {
            case 'viewer':
                const doc = documents.find(d => d.id === selectedDocumentId);
                return doc ? <DocumentViewer document={doc} onUpdate={handleUpdateDocument} onBack={handleHomeClick} /> : <p>Document not found.</p>;
            
             case 'compliance':
                return <ComplianceJourney documents={documents} policies={policies} onBack={handleHomeClick} />;

            case 'documentList':
                return <DocumentList documents={documents} onView={handleViewDocument} />;

            case 'liveAssistant':
                return <LiveAssistant />;
            
            case 'riskAssessment':
                return <RiskAssessment setView={setView} />;

            case 'complianceDashboard':
            default:
                return <ComplianceDashboard documents={documents} policies={policies} onView={handleViewDocument} />;
        }
    };
    
    return (
        <div className="min-h-screen bg-gray-900 text-white font-sans overflow-hidden relative">
            <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2">
                <div className="w-[80vw] h-[80vh] bg-gradient-to-tr from-sky-400 via-sky-600 to-teal-400 rounded-full blur-[150px] opacity-20 animate-pulse"></div>
            </div>
            
            <div className="relative z-10 flex h-screen">
                <Sidebar currentView={currentView} setView={setView} />
                <div className="flex-grow flex flex-col overflow-hidden">
                    <Header onHomeClick={handleHomeClick}/>
                    <main className="flex-grow flex p-4 md:p-8 overflow-hidden">
                        {renderContent()}
                    </main>
                </div>
            </div>
        </div>
    );
};

export default App;
